swagger: "2.0"
info:
  title: Notes API
  description: Swagger for Notes Application.
  version: 1.0.0
tags:
- name: "User Actions"
  description: "Login & Signup actions"
- name: "Note Actions"
  description: "Add, Edit & Delete action on Notes"
paths:
  /Signup:
    post:
      tags: [User Actions]
      summary: Register a new user.
      parameters: 
        - in: "body"
          required: true
          schema:
            type: object
            required: [fname, lname, email, password]
            properties:
              fname:
                type: string
              lname:
                type: string
              email:
                type: string
              password:
                type: string
      description: Register a new user & get that object back.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /Login:
    get:
      tags: [User Actions]
      summary: Returns a list of users.
      parameters:
        - in: body
          description: The user to create.
          schema:
            type: object
            required: [email, password]
            properties:
              email:
                type: string
              password:
                type: string
      description: Login the user & return the Logged in Object.
      produces:
        - application/json
      responses:
        200:
          description: OK
