swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
paths:
  /Signin:
    post:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /login:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      parameters:
        - in: body
          # name: user
          description: The user to create.
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: OK
